import { useEffect, useMemo, useState } from "react";
import { Check, Clipboard, Download, FileLock2, Globe2, Info, LockKeyhole, RefreshCw, ShieldCheck, Sparkles, Trash2, UnlockKeyhole } from "lucide-react";
import { toast } from "sonner";

const languages = [
  ["en", "English (EN)"], ["tr", "Türkçe (TR)"], ["de", "Deutsch (DE)"], ["fr", "Français (FR)"], ["es", "Español (ES)"], ["it", "Italiano (IT)"],
  ["nl", "Nederlands (NL)"], ["sv", "Svenska (SV)"], ["da", "Dansk (DA)"], ["no", "Norsk (NO)"], ["fi", "Suomi (FI)"], ["zh", "中文 (ZH)"],
] as const;

type Locale = typeof languages[number][0];
type Strings = { eyebrow: string; title: string; intro: string; private: string; privateText: string; note: string; password: string; passwordPlaceholder: string; notePlaceholder: string; encrypt: string; decrypt: string; clear: string; copy: string; download: string; output: string; outputHint: string; local: string; localText: string; how: string; howText: string; important: string; importantText: string; security: string; securityText: string; back: string; ready: string; encrypted: string; decrypted: string; passwordRequired: string; invalid: string; copied: string; empty: string; };

const strings: Record<Locale, Strings> = {
  en: { eyebrow: "PRIVATE CLIENT-SIDE TOOL", title: "Secure Note", intro: "Encrypt a private note in your browser. Nothing is uploaded, stored, or sent to a server.", private: "Your note stays private", privateText: "Secure Note uses Web Crypto API with AES-256-GCM. Your password never leaves this device.", note: "Note", password: "Password", passwordPlaceholder: "Use a strong password", notePlaceholder: "Write your private note here...", encrypt: "Encrypt note", decrypt: "Decrypt bundle", clear: "Clear", copy: "Copy", download: "Download", output: "Encrypted output", outputHint: "Copy this bundle and keep it with your password.", local: "Local by default", localText: "The entire operation runs in your browser. There are no accounts, uploads, or tracking scripts.", how: "How it works", howText: "Your note is encrypted with a key derived from your password. The encrypted bundle contains only the data needed to decrypt it later.", important: "Important", importantText: "If you lose your password, the note cannot be recovered. Secure Note is a private utility, not a replacement for a password manager.", security: "AES-256-GCM", securityText: "Modern browser encryption", back: "Open tool", ready: "Ready when you are", encrypted: "Note encrypted locally", decrypted: "Note decrypted locally", passwordRequired: "Add a password first.", invalid: "This bundle or password could not be verified.", copied: "Encrypted bundle copied.", empty: "Write a note first." },
  tr: { eyebrow: "GİZLİLİK ÖNCELİKLİ ARAÇ", title: "Şifreli Not", intro: "Özel notunuzu tarayıcınızda şifreleyin. Hiçbir veri yüklenmez, saklanmaz veya sunucuya gönderilmez.", private: "Notunuz gizli kalır", privateText: "Şifreli Not, AES-256-GCM ile Web Crypto API kullanır. Parolanız cihazınızdan çıkmaz.", note: "Not", password: "Parola", passwordPlaceholder: "Güçlü bir parola kullanın", notePlaceholder: "Özel notunuzu buraya yazın...", encrypt: "Notu şifrele", decrypt: "Paketi çöz", clear: "Temizle", copy: "Kopyala", download: "İndir", output: "Şifreli çıktı", outputHint: "Bu paketi kopyalayın ve parolanızla birlikte saklayın.", local: "Varsayılan olarak yerel", localText: "Tüm işlem tarayıcınızda gerçekleşir. Hesap, yükleme veya takip kodu yoktur.", how: "Nasıl çalışır?", howText: "Notunuz parolanızdan türetilen bir anahtarla şifrelenir. Şifreli paket daha sonra çözmek için gereken veriyi içerir.", important: "Önemli", importantText: "Parolanızı kaybederseniz not kurtarılamaz. Şifreli Not, parola yöneticisinin yerine geçmez.", security: "AES-256-GCM", securityText: "Modern tarayıcı şifrelemesi", back: "Aracı aç", ready: "Hazır olduğunuzda", encrypted: "Not yerel olarak şifrelendi", decrypted: "Not yerel olarak çözüldü", passwordRequired: "Önce bir parola ekleyin.", invalid: "Bu paket veya parola doğrulanamadı.", copied: "Şifreli paket kopyalandı.", empty: "Önce bir not yazın." },
  de: { eyebrow: "PRIVATES BROWSER-TOOL", title: "Sichere Notiz", intro: "Verschlüsseln Sie eine private Notiz direkt im Browser. Nichts wird hochgeladen oder an einen Server gesendet.", private: "Ihre Notiz bleibt privat", privateText: "Secure Note nutzt die Web Crypto API mit AES-256-GCM. Ihr Passwort verlässt dieses Gerät nie.", note: "Notiz", password: "Passwort", passwordPlaceholder: "Starkes Passwort verwenden", notePlaceholder: "Private Notiz hier schreiben...", encrypt: "Notiz verschlüsseln", decrypt: "Bundle entschlüsseln", clear: "Löschen", copy: "Kopieren", download: "Download", output: "Verschlüsselte Ausgabe", outputHint: "Bundle kopieren und mit dem Passwort aufbewahren.", local: "Lokal standardmäßig", localText: "Alles läuft im Browser. Keine Konten, Uploads oder Tracking-Skripte.", how: "So funktioniert es", howText: "Die Notiz wird mit einem aus Ihrem Passwort abgeleiteten Schlüssel verschlüsselt.", important: "Wichtig", importantText: "Ohne Passwort kann die Notiz nicht wiederhergestellt werden.", security: "AES-256-GCM", securityText: "Moderne Browser-Verschlüsselung", back: "Tool öffnen", ready: "Bereit", encrypted: "Notiz lokal verschlüsselt", decrypted: "Notiz lokal entschlüsselt", passwordRequired: "Passwort hinzufügen.", invalid: "Bundle oder Passwort konnte nicht geprüft werden.", copied: "Bundle kopiert.", empty: "Zuerst eine Notiz schreiben." },
  fr: { eyebrow: "OUTIL PRIVÉ DANS LE NAVIGATEUR", title: "Note sécurisée", intro: "Chiffrez une note privée dans votre navigateur. Rien n'est envoyé à un serveur.", private: "Votre note reste privée", privateText: "Secure Note utilise Web Crypto et AES-256-GCM. Votre mot de passe ne quitte jamais cet appareil.", note: "Note", password: "Mot de passe", passwordPlaceholder: "Utilisez un mot de passe fort", notePlaceholder: "Écrivez votre note privée ici...", encrypt: "Chiffrer la note", decrypt: "Déchiffrer le bundle", clear: "Effacer", copy: "Copier", download: "Télécharger", output: "Sortie chiffrée", outputHint: "Copiez ce bundle et gardez-le avec votre mot de passe.", local: "Local par défaut", localText: "Tout fonctionne dans le navigateur, sans compte ni téléchargement.", how: "Fonctionnement", howText: "La note est chiffrée avec une clé dérivée de votre mot de passe.", important: "Important", importantText: "Sans votre mot de passe, la note ne peut pas être récupérée.", security: "AES-256-GCM", securityText: "Chiffrement moderne du navigateur", back: "Ouvrir l'outil", ready: "Prêt", encrypted: "Note chiffrée localement", decrypted: "Note déchiffrée localement", passwordRequired: "Ajoutez un mot de passe.", invalid: "Bundle ou mot de passe invalide.", copied: "Bundle copié.", empty: "Écrivez d'abord une note." },
  es: { eyebrow: "HERRAMIENTA PRIVADA EN EL NAVEGADOR", title: "Nota segura", intro: "Cifra una nota privada en tu navegador. Nada se sube ni se envía a un servidor.", private: "Tu nota permanece privada", privateText: "Secure Note usa Web Crypto API con AES-256-GCM. Tu contraseña nunca sale de este dispositivo.", note: "Nota", password: "Contraseña", passwordPlaceholder: "Usa una contraseña segura", notePlaceholder: "Escribe tu nota privada aquí...", encrypt: "Cifrar nota", decrypt: "Descifrar paquete", clear: "Borrar", copy: "Copiar", download: "Descargar", output: "Salida cifrada", outputHint: "Copia este paquete y guárdalo con tu contraseña.", local: "Local por defecto", localText: "Todo funciona en tu navegador. Sin cuentas, subidas ni seguimiento.", how: "Cómo funciona", howText: "La nota se cifra con una clave derivada de tu contraseña.", important: "Importante", importantText: "Si pierdes tu contraseña, la nota no se puede recuperar.", security: "AES-256-GCM", securityText: "Cifrado moderno del navegador", back: "Abrir herramienta", ready: "Listo", encrypted: "Nota cifrada localmente", decrypted: "Nota descifrada localmente", passwordRequired: "Añade una contraseña.", invalid: "No se pudo verificar el paquete o la contraseña.", copied: "Paquete copiado.", empty: "Escribe una nota primero." },
  it: { eyebrow: "STRUMENTO PRIVATO NEL BROWSER", title: "Nota sicura", intro: "Cripta una nota privata nel browser. Nulla viene caricato o inviato a un server.", private: "La tua nota resta privata", privateText: "Secure Note usa Web Crypto API con AES-256-GCM. La password non lascia mai questo dispositivo.", note: "Nota", password: "Password", passwordPlaceholder: "Usa una password sicura", notePlaceholder: "Scrivi qui la tua nota privata...", encrypt: "Cripta nota", decrypt: "Decripta pacchetto", clear: "Cancella", copy: "Copia", download: "Scarica", output: "Output criptato", outputHint: "Copia il pacchetto e conservalo con la password.", local: "Locale per impostazione predefinita", localText: "Tutto funziona nel browser, senza account, upload o tracking.", how: "Come funziona", howText: "La nota viene criptata con una chiave derivata dalla password.", important: "Importante", importantText: "Se perdi la password, la nota non può essere recuperata.", security: "AES-256-GCM", securityText: "Crittografia moderna del browser", back: "Apri strumento", ready: "Pronto", encrypted: "Nota criptata localmente", decrypted: "Nota decriptata localmente", passwordRequired: "Aggiungi una password.", invalid: "Pacchetto o password non validi.", copied: "Pacchetto copiato.", empty: "Scrivi prima una nota." },
  nl: { eyebrow: "PRIVÉTOOL IN DE BROWSER", title: "Veilige notitie", intro: "Versleutel een privénotitie in je browser. Er wordt niets geüpload of verzonden.", private: "Je notitie blijft privé", privateText: "Secure Note gebruikt Web Crypto API met AES-256-GCM. Je wachtwoord verlaat dit apparaat niet.", note: "Notitie", password: "Wachtwoord", passwordPlaceholder: "Gebruik een sterk wachtwoord", notePlaceholder: "Schrijf hier je privénotitie...", encrypt: "Notitie versleutelen", decrypt: "Bundel ontsleutelen", clear: "Wissen", copy: "Kopiëren", download: "Downloaden", output: "Versleutelde uitvoer", outputHint: "Kopieer deze bundel en bewaar hem met je wachtwoord.", local: "Standaard lokaal", localText: "Alles gebeurt in je browser, zonder accounts, uploads of tracking.", how: "Hoe het werkt", howText: "De notitie wordt versleuteld met een sleutel die van je wachtwoord is afgeleid.", important: "Belangrijk", importantText: "Zonder je wachtwoord kan de notitie niet worden hersteld.", security: "AES-256-GCM", securityText: "Moderne browserversleuteling", back: "Tool openen", ready: "Klaar", encrypted: "Notitie lokaal versleuteld", decrypted: "Notitie lokaal ontsleuteld", passwordRequired: "Voeg eerst een wachtwoord toe.", invalid: "Bundel of wachtwoord kon niet worden gecontroleerd.", copied: "Bundel gekopieerd.", empty: "Schrijf eerst een notitie." },
  sv: { eyebrow: "PRIVAT WEBBLÄSARVERKTYG", title: "Säker anteckning", intro: "Kryptera en privat anteckning i webbläsaren. Inget laddas upp eller skickas till en server.", private: "Din anteckning förblir privat", privateText: "Secure Note använder Web Crypto API med AES-256-GCM. Ditt lösenord lämnar aldrig enheten.", note: "Anteckning", password: "Lösenord", passwordPlaceholder: "Använd ett starkt lösenord", notePlaceholder: "Skriv din privata anteckning här...", encrypt: "Kryptera anteckning", decrypt: "Dekryptera paket", clear: "Rensa", copy: "Kopiera", download: "Ladda ner", output: "Krypterad utdata", outputHint: "Kopiera paketet och spara det med lösenordet.", local: "Lokalt som standard", localText: "Allt körs i webbläsaren utan konton, uppladdningar eller spårning.", how: "Så fungerar det", howText: "Anteckningen krypteras med en nyckel som härleds från ditt lösenord.", important: "Viktigt", importantText: "Utan lösenordet kan anteckningen inte återställas.", security: "AES-256-GCM", securityText: "Modern webbläsarkryptering", back: "Öppna verktyget", ready: "Redo", encrypted: "Anteckningen krypterades lokalt", decrypted: "Anteckningen dekrypterades lokalt", passwordRequired: "Lägg till ett lösenord.", invalid: "Paketet eller lösenordet kunde inte verifieras.", copied: "Paketet kopierades.", empty: "Skriv en anteckning först." },
  da: { eyebrow: "PRIVAT VÆRKTØJ I BROWSEREN", title: "Sikker note", intro: "Kryptér en privat note i din browser. Intet uploades eller sendes til en server.", private: "Din note forbliver privat", privateText: "Secure Note bruger Web Crypto API med AES-256-GCM. Din adgangskode forlader aldrig enheden.", note: "Note", password: "Adgangskode", passwordPlaceholder: "Brug en stærk adgangskode", notePlaceholder: "Skriv din private note her...", encrypt: "Kryptér note", decrypt: "Dekryptér pakke", clear: "Ryd", copy: "Kopiér", download: "Download", output: "Krypteret output", outputHint: "Kopiér pakken og gem den med adgangskoden.", local: "Lokal som standard", localText: "Alt kører i browseren uden konti, uploads eller sporing.", how: "Sådan virker det", howText: "Noten krypteres med en nøgle afledt af din adgangskode.", important: "Vigtigt", importantText: "Uden adgangskoden kan noten ikke gendannes.", security: "AES-256-GCM", securityText: "Moderne browserkryptering", back: "Åbn værktøj", ready: "Klar", encrypted: "Note krypteret lokalt", decrypted: "Note dekrypteret lokalt", passwordRequired: "Tilføj en adgangskode.", invalid: "Pakken eller adgangskoden kunne ikke verificeres.", copied: "Pakke kopieret.", empty: "Skriv en note først." },
  no: { eyebrow: "PRIVAT VERKTØY I NETTLESEREN", title: "Sikkert notat", intro: "Krypter et privat notat i nettleseren. Ingenting lastes opp eller sendes til en server.", private: "Notatet ditt forblir privat", privateText: "Secure Note bruker Web Crypto API med AES-256-GCM. Passordet forlater aldri enheten.", note: "Notat", password: "Passord", passwordPlaceholder: "Bruk et sterkt passord", notePlaceholder: "Skriv det private notatet her...", encrypt: "Krypter notat", decrypt: "Dekrypter pakke", clear: "Tøm", copy: "Kopier", download: "Last ned", output: "Kryptert resultat", outputHint: "Kopier pakken og oppbevar den med passordet.", local: "Lokalt som standard", localText: "Alt kjører i nettleseren uten kontoer, opplastinger eller sporing.", how: "Slik fungerer det", howText: "Notatet krypteres med en nøkkel som er avledet fra passordet.", important: "Viktig", importantText: "Uten passordet kan notatet ikke gjenopprettes.", security: "AES-256-GCM", securityText: "Moderne nettleserkryptering", back: "Åpne verktøy", ready: "Klar", encrypted: "Notatet er kryptert lokalt", decrypted: "Notatet er dekryptert lokalt", passwordRequired: "Legg til et passord.", invalid: "Pakken eller passordet kunne ikke bekreftes.", copied: "Pakke kopiert.", empty: "Skriv et notat først." },
  fi: { eyebrow: "YKSITYINEN SELAIN-TOIMINTO", title: "Suojattu muistiinpano", intro: "Salaa yksityinen muistiinpano selaimessasi. Mitään ei ladata tai lähetetä palvelimelle.", private: "Muistiinpanosi pysyy yksityisenä", privateText: "Secure Note käyttää Web Crypto API:a ja AES-256-GCM:ää. Salasanasi ei poistu laitteelta.", note: "Muistiinpano", password: "Salasana", passwordPlaceholder: "Käytä vahvaa salasanaa", notePlaceholder: "Kirjoita yksityinen muistiinpano tähän...", encrypt: "Salaa muistiinpano", decrypt: "Pura paketin salaus", clear: "Tyhjennä", copy: "Kopioi", download: "Lataa", output: "Salattu tulos", outputHint: "Kopioi paketti ja säilytä se salasanan kanssa.", local: "Paikallinen oletuksena", localText: "Kaikki tapahtuu selaimessa ilman tilejä, latauksia tai seurantaa.", how: "Miten se toimii", howText: "Muistiinpano salataan salasanasta johdetulla avaimella.", important: "Tärkeää", importantText: "Ilman salasanaa muistiinpanoa ei voi palauttaa.", security: "AES-256-GCM", securityText: "Moderni selaimen salaus", back: "Avaa työkalu", ready: "Valmis", encrypted: "Muistiinpano salattiin paikallisesti", decrypted: "Muistiinpano avattiin paikallisesti", passwordRequired: "Lisää ensin salasana.", invalid: "Pakettia tai salasanaa ei voitu vahvistaa.", copied: "Paketti kopioitu.", empty: "Kirjoita ensin muistiinpano." },
  zh: { eyebrow: "浏览器本地隐私工具", title: "安全便笺", intro: "在浏览器中加密私人便笺。内容不会上传、存储或发送到服务器。", private: "便笺保持私密", privateText: "Secure Note 使用 Web Crypto API 和 AES-256-GCM 加密，密码不会离开设备。", note: "便笺", password: "密码", passwordPlaceholder: "请输入强密码", notePlaceholder: "在此写下私人便笺...", encrypt: "加密便笺", decrypt: "解密数据包", clear: "清除", copy: "复制", download: "下载", output: "加密输出", outputHint: "复制此数据包并与密码一起保存。", local: "默认本地处理", localText: "所有操作都在浏览器中完成，无需账号、上传或追踪。", how: "工作原理", howText: "便笺使用由密码派生的密钥进行加密。", important: "重要提示", importantText: "如果忘记密码，便笺无法恢复。", security: "AES-256-GCM", securityText: "现代浏览器加密", back: "打开工具", ready: "准备就绪", encrypted: "便笺已在本地加密", decrypted: "便笺已在本地解密", passwordRequired: "请先添加密码。", invalid: "无法验证数据包或密码。", copied: "数据包已复制。", empty: "请先写一条便笺。" },
};

const encoder = new TextEncoder();
const decoder = new TextDecoder();
const toBase64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...Array.from(bytes)));
const fromBase64 = (value: string) => Uint8Array.from(atob(value), char => char.charCodeAt(0));

async function deriveKey(password: string, salt: Uint8Array) {
  const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]);
  return crypto.subtle.deriveKey({ name: "PBKDF2", salt, iterations: 250000, hash: "SHA-256" }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);
}

function detectLocale(): Locale { const route = window.location.pathname.split("/")[1] as Locale; return languages.some(([code]) => code === route) ? route : "en"; }

export default function App() {
  const [locale, setLocale] = useState<Locale>(detectLocale());
  const copy = strings[locale];
  const [note, setNote] = useState("");
  const [password, setPassword] = useState("");
  const [output, setOutput] = useState("");
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);
  const isEncrypted = useMemo(() => output.startsWith("PRATIX1."), [output]);

  useEffect(() => { document.documentElement.lang = locale; document.title = `${copy.title} — Pratix.io`; }, [copy.title, locale]);

  const changeLocale = (value: Locale) => { setLocale(value); window.history.replaceState({}, "", `/${value}/secure-note`); };
  const encrypt = async () => { if (!password) return toast.error(copy.passwordRequired); if (!note.trim()) return toast.error(copy.empty); setBusy(true); try { const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const key = await deriveKey(password, salt); const cipher = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, encoder.encode(note)); const bundle = `PRATIX1.${toBase64(salt)}.${toBase64(iv)}.${toBase64(new Uint8Array(cipher))}`; setOutput(bundle); setNote(""); setStatus(copy.encrypted); toast.success(copy.encrypted); } finally { setBusy(false); } };
  const decrypt = async () => { if (!password) return toast.error(copy.passwordRequired); if (!output.startsWith("PRATIX1.")) return toast.error(copy.invalid); setBusy(true); try { const [, salt64, iv64, cipher64] = output.split("."); const key = await deriveKey(password, fromBase64(salt64)); const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(iv64) }, key, fromBase64(cipher64)); setNote(decoder.decode(plain)); setStatus(copy.decrypted); toast.success(copy.decrypted); } catch { toast.error(copy.invalid); } finally { setBusy(false); } };
  const clear = () => { setNote(""); setPassword(""); setOutput(""); setStatus(""); };
  const copyOutput = async () => { if (!output) return; await navigator.clipboard.writeText(output); toast.success(copy.copied); };
  const download = () => { if (!output) return; const blob = new Blob([output], { type: "text/plain" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "pratix-secure-note.txt"; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="app-shell"><header className="site-header"><a href="https://www.pratix.io/" className="brand"><span className="brand-mark">P</span><span><b>pratix</b><strong>.io</strong><small>Practical Micro-SaaS Tools</small></span></a><div className="header-actions"><a href="https://www.pratix.io/" className="open-tool">{copy.back}</a><div className="language-control"><Globe2 size={14}/><select value={locale} onChange={e => changeLocale(e.target.value as Locale)} aria-label="Language">{languages.map(([code, label]) => <option value={code} key={code}>{label}</option>)}</select></div></div></header>
    <main><section className="hero"><div className="hero-copy"><span className="eyebrow"><i></i>{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p><div className="hero-pills"><span><LockKeyhole size={14}/> {copy.security}</span><span><ShieldCheck size={14}/> {copy.local}</span><span><FileLock2 size={14}/> No uploads</span></div></div><div className="hero-card"><span className="card-kicker">PRATIX / PRIVACY</span><div className="card-icon"><LockKeyhole size={23}/></div><h2>{copy.private}</h2><p>{copy.privateText}</p><div className="card-footer"><span><span className="pulse-dot"></span> {copy.ready}</span><span>v1.0</span></div></div></section>
      <section className="tool-layout" id="tool"><div className="workspace"><div className="workspace-header"><div><span className="section-label">SECURE WORKSPACE</span><h2>{copy.note}</h2></div><button className="clear-button" onClick={clear}><Trash2 size={14}/> {copy.clear}</button></div><label>{copy.note}</label><textarea value={note} onChange={e => setNote(e.target.value)} placeholder={copy.notePlaceholder} spellCheck="false"/><div className="password-row"><label>{copy.password}</label><input value={password} onChange={e => setPassword(e.target.value)} placeholder={copy.passwordPlaceholder} type="password" autoComplete="off"/><span className="password-hint"><LockKeyhole size={13}/> never leaves your device</span></div><div className="action-row"><button className="primary-button" onClick={encrypt} disabled={busy}><LockKeyhole size={16}/>{busy ? "..." : copy.encrypt}</button><button className="secondary-button" onClick={decrypt} disabled={busy}><UnlockKeyhole size={16}/>{copy.decrypt}</button></div>{status && <div className="status-line"><Check size={15}/> {status}</div>}</div><aside className="output-panel"><div className="output-head"><div><span className="section-label">{copy.output}</span><h3>{output ? "PRATIX1 bundle" : "—"}</h3></div>{output && <span className="valid-badge"><Check size={12}/> local</span>}</div><p>{copy.outputHint}</p><pre>{output || "Your encrypted bundle will appear here."}</pre><div className="output-actions"><button onClick={copyOutput} disabled={!output}><Clipboard size={14}/> {copy.copy}</button><button onClick={download} disabled={!output}><Download size={14}/> {copy.download}</button></div></aside></section>
      <section className="info-grid"><article><div className="info-icon"><ShieldCheck size={19}/></div><span className="section-label">01 / {copy.local}</span><h2>{copy.local}</h2><p>{copy.localText}</p></article><article><div className="info-icon"><Sparkles size={19}/></div><span className="section-label">02 / {copy.how}</span><h2>{copy.how}</h2><p>{copy.howText}</p></article><article className="important"><div className="info-icon"><Info size={19}/></div><span className="section-label">03 / {copy.important}</span><h2>{copy.important}</h2><p>{copy.importantText}</p></article></section>
      <section className="seo-section"><span className="section-label">PRIVACY-FIRST UTILITY</span><h2>A simple encrypted note for everyday work.</h2><p>Secure Note is a small browser utility for private drafts, temporary secrets, checklists, and sensitive working notes. Encryption happens on your device with Web Crypto API. Pratix does not ask for an account, a file upload, or a tracking script before you can use the tool.</p><div className="seo-links"><a href="https://www.pratix.io/">Explore all Pratix tools →</a><a href="https://www.pratix.io/en/">English tools</a><a href="https://www.pratix.io/tr/">Türkçe araçlar</a></div></section>
    </main><footer><a href="https://www.pratix.io/" className="brand"><span className="brand-mark">P</span><span><b>pratix</b><strong>.io</strong></span></a><span>Privacy-first tools for everyday work.</span><span>© 2026 Pratix.io</span></footer></div>;
}
