import { Link } from "wouter";
import { ArrowLeft, ArrowRight, Globe2, LockKeyhole, ShieldCheck } from "lucide-react";

const articles: Record<string, { label: string; title: string; intro: string; keywords: string; blocks: { h: string; p: string }[] }> = {
  en: { label: "PRATIX GUIDE / PRIVACY", title: "Why privacy-first tools are becoming the practical default", intro: "People do not need another complicated productivity suite. They need small utilities that solve a real problem without asking for their files, identity, or attention. Privacy-first web tools are built around that simple promise: useful output, minimal friction, and local processing whenever the browser can do the work.", keywords: "privacy-first tools, secure note, client-side tools, browser privacy, encrypted notes", blocks: [
    { h: "What does privacy-first mean in practice?", p: "Privacy-first is more than a badge or a policy page. It is a product decision to keep data collection out of the critical path. For a browser tool, that means text, documents, campaign links, passwords, or calculations can be processed locally before a server is ever considered. The result is faster interaction, fewer breach concerns, and a clearer relationship with the person using the tool." },
    { h: "A secure note is a useful starting point", p: "A secure note tool is one of the clearest examples of local-first design. A user can write a temporary secret, a private checklist, a recovery phrase reminder, or a sensitive draft, encrypt it in the browser, and copy or download the result only when they choose. The interface should explain what happens, use modern Web Crypto primitives, and avoid pretending that a browser tool is a replacement for a managed password manager." },
    { h: "Why small utilities earn trust", p: "The best free tools are direct. They show an input, an operation, and an output. They do not hide a registration wall behind a simple task. For creators, sellers, developers, and independent teams, that clarity matters because many tasks happen in the middle of a busy workflow: checking a JSON payload, creating a UTM link, calculating a freelance rate, or writing a note that should not be uploaded." },
    { h: "Local processing is also a performance advantage", p: "When a tool does not need to upload an input, it can often return a result immediately. That reduces network dependency and makes the experience more resilient on mobile connections. It also creates a strong SEO and product message: the tool is free, fast, and private by default. Those benefits are easy to understand across languages and markets." },
    { h: "How to choose the right privacy-first tool", p: "Start with the sensitivity of the input. If the content is personal, commercial, or confidential, prefer a tool that clearly states where processing happens. Next, check whether the result is reversible and exportable. Finally, choose the smallest tool that completes the job. A focused secure note, calculator, or formatter can be more trustworthy than a large workspace that quietly collects everything." },
    { h: "The Pratix approach", p: "Pratix is building a multilingual ecosystem of practical web tools for everyday work. The roadmap begins with low-competition utilities that have a clear audience and a strong privacy difference: secure notes, campaign builders, readability checks, rate calculators, developer formatters, and commerce helpers. Each tool is designed to be useful on day one, accessible in twelve languages, and ready to connect into deeper workflows over time." },
  ] },
  tr: { label: "PRATIX REHBERİ / GİZLİLİK", title: "Gizlilik öncelikli araçlar neden pratik varsayılan oluyor?", intro: "İnsanların bir başka karmaşık üretkenlik paketine ihtiyacı yok. Dosyalarını, kimliklerini veya dikkatlerini istemeden gerçek bir sorunu çözen küçük araçlara ihtiyaçları var. Gizlilik öncelikli web araçları bu basit vaade dayanır: faydalı çıktı, az sürtünme ve tarayıcı işi yapabildiğinde yerel işlem.", keywords: "gizlilik öncelikli araçlar, şifreli not, client-side araçlar, tarayıcı gizliliği, güvenli not", blocks: [
    { h: "Gizlilik öncelikli olmak pratikte ne demektir?", p: "Gizlilik yalnızca bir rozet veya politika sayfası değildir. Kritik akıştan veri toplamayı çıkarmak bir ürün kararıdır. Metin, dosya, kampanya bağlantısı, şifre veya hesaplama mümkünse sunucuya gitmeden tarayıcıda işlenir. Böylece etkileşim hızlanır, veri sızıntısı endişesi azalır ve kullanıcı ile ürün arasındaki ilişki netleşir." },
    { h: "Şifreli not iyi bir başlangıçtır", p: "Şifreli not aracı yerel öncelikli tasarımın anlaşılır bir örneğidir. Kullanıcı geçici bir sırrı, özel kontrol listesini veya hassas taslağı tarayıcıda şifreleyebilir; sonucu yalnızca istediğinde kopyalar ya da indirir. Arayüz ne olduğunu açıkça anlatmalı, Web Crypto kullanmalı ve tarayıcı aracının parola yöneticisinin yerine geçmediğini dürüstçe belirtmelidir." },
    { h: "Küçük araçlar nasıl güven kazanır?", p: "İyi ücretsiz araçlar doğrudandır: girdi, işlem ve çıktı. Basit bir görevin arkasına kayıt duvarı koymaz. Satıcılar, içerik üreticileri, geliştiriciler ve bağımsız ekipler için bu açıklık önemlidir; JSON kontrolü, UTM bağlantısı, freelance ücret hesabı veya yüklenmemesi gereken bir not çoğu zaman yoğun bir iş akışının ortasında yapılır." },
    { h: "Yerel işlem performans avantajıdır", p: "Bir araç girdiyi yüklemek zorunda değilse sonucu daha hızlı verebilir. Bu durum mobil bağlantılarda dayanıklılığı artırır. Aynı zamanda güçlü bir ürün ve SEO mesajı oluşturur: araç ücretsiz, hızlı ve varsayılan olarak gizlidir." },
    { h: "Doğru gizlilik aracını nasıl seçersiniz?", p: "Önce girdinin hassasiyetine bakın. Kişisel, ticari veya gizli içerik için işlemin nerede yapıldığını açıkça söyleyen bir araç seçin. Sonucun dışa aktarılabilir olmasına dikkat edin ve işi tamamlayan en küçük aracı tercih edin." },
    { h: "Pratix yaklaşımı", p: "Pratix günlük işler için çok dilli pratik web araçları ekosistemi kuruyor. Yol haritası Secure Note, kampanya oluşturucu, okunabilirlik kontrolü, ücret hesaplayıcı, geliştirici biçimlendiricileri ve ticaret yardımcıları gibi niş ve gizlilik farkı güçlü araçlarla başlıyor. Her araç ilk günden faydalı, 12 dilde erişilebilir ve ileride daha derin iş akışlarına bağlanabilir olacak." },
  ] },
};

const fallback: Record<string, string> = { de: "Datenschutzorientierte Webtools für den Alltag", es: "Herramientas web centradas en la privacidad para el trabajo diario", fr: "Des outils web axés sur la confidentialité pour le quotidien", it: "Strumenti web orientati alla privacy per il lavoro quotidiano", pt: "Ferramentas web com privacidade para o trabalho diário", nl: "Privacygerichte webtools voor dagelijks werk", pl: "Narzędzia internetowe z ochroną prywatności na co dzień", ja: "日常の仕事のためのプライバシー重視のWebツール", ko: "일상 업무를 위한 개인정보 보호 중심 웹 도구", ar: "أدوات ويب تضع الخصوصية أولاً للعمل اليومي" };

export default function SeoArticle({ locale = "en" }: { locale?: string }) {
  const article = articles[locale] || articles.en;
  const localizedTitle = article.title || fallback[locale] || articles.en.title;
  return <main className="article-page"><div className="article-wrap"><Link href={`/${locale}/`} className="back-link"><ArrowLeft size={15}/> Pratix.io</Link><div className="article-header"><span className="section-kicker">{article.label}</span><h1>{localizedTitle}</h1><p className="article-intro">{article.intro}</p><div className="article-meta"><span><LockKeyhole size={14}/> Local-first</span><span><Globe2 size={14}/> 12 languages</span><span><ShieldCheck size={14}/> No uploads by default</span></div></div><div className="article-body"><aside><div className="toc-label">IN THIS GUIDE</div><a href="#meaning">Privacy-first basics</a><a href="#secure-note">Privacy principles</a><a href="#trust">Trust & performance</a><a href="#pratix">The Pratix approach</a></aside><article><div className="keyword-box"><b>SEO focus:</b> {article.keywords}</div>{article.blocks.map((block, i) => <section id={i === 0 ? "meaning" : i === 1 ? "secure-note" : i === 2 ? "trust" : i === 5 ? "pratix" : undefined} key={block.h}><h2>{block.h}</h2><p>{block.p}</p></section>)}<div className="article-cta"><div><span className="section-kicker">NEXT STEP</span><h3>Use the practical toolkit.</h3><p>Start with a focused utility and keep your workflow simple.</p></div><Link href={`/${locale}/tools/utm-builder`} className="button primary">Open UTM Builder <ArrowRight size={16}/></Link></div></article></div></div></main>;
}
